version: '2.1'
services:
    zookeeper:
      image: zookeeper:3.4.9
      hostname: zookeeper
      ports:
        - "2181:2181"
      environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zookeeper1:2888:3888
      volumes:
      - ./mapped-volume/zookeeper1/data:/data
      - ./mapped-volume/zookeeper1/datalog:/datalog

    kafka:
      image: confluentinc/cp-kafka:5.3.0
      hostname: kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_BROKER_ID: 1
        KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      volumes:
        - ./mapped-volume/kafka/data:/var/lib/kafka/data
      depends_on:
        - zookeeper
    spark-master:
      image: ldev/spark:v0.1.0
      container_name: spark-master
      hostname: spark-master
      ports:
        - "8080:8080"
        - "7077:7077"
      environment:
        - "SPARK_LOCAL_IP=spark-master"
        - "SPARK_MASTER_PORT=7077"
        - "SPARK_MASTER_WEBUI_PORT=8080"
      command: "/start-master.sh"
    
    spark-worker:
      image: ldev/spark:v0.1.0
      depends_on:
        - spark-master
      ports:
        - 8080
      environment:
        - "SPARK_MASTER=spark://spark-master:7077"
        - "SPARK_WORKER_WEBUI_PORT=8080"
      command: "/start-worker.sh"